// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYPJY7S2NKMXy06uFTZ4CDJPxPFsOWAbw',
    appId: '1:19171134555:web:a6533a46e4b621f43ec37e',
    messagingSenderId: '19171134555',
    projectId: 'moments-5f251',
    authDomain: 'moments-5f251.firebaseapp.com',
    storageBucket: 'moments-5f251.appspot.com',
    measurementId: 'G-L686CF802S',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUYwBOL4QoYe0Cj8YfKQzKa94PqIzf-Tg',
    appId: '1:19171134555:ios:4b07dbf2f27ee59f3ec37e',
    messagingSenderId: '19171134555',
    projectId: 'moments-5f251',
    storageBucket: 'moments-5f251.appspot.com',
    iosClientId: '19171134555-25orq6ee06r3sh8fp8tcavi640l1on25.apps.googleusercontent.com',
    iosBundleId: 'com.moments.app',
  );
}
